[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; --- IMPOSTAZIONI OTA E MONITOR WIFI ---
upload_protocol = espota
upload_port = 192.168.1.76
monitor_port = socket://192.168.1.76:23  ; <--- FONDAMENTALE PER IL MONITOR
; --------------------------------------

board_build.partitions = default_ota.csv
lib_deps = 
    liquidcrystal_i2c
    keypad
    preferences
    Wire
    SPI
    RTClib
    adafruit/Adafruit BusIO
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit NeoPixel
    adafruit/Adafruit SSD1306
    bblanchon/ArduinoJson
    jandrassy/TelnetStream    ; <--- NUOVA LIBRERIA